<?php
$pageSlug = (string) ($_GET['page'] ?? 'parametres_generaux');

cm_render_param_crud_view([
    'page_slug' => $pageSlug,
    'action' => 'entreprises',
    'title' => '',
    'icon' => 'fa-building',
    'form_title_add' => '',
    'form_title_edit' => '',
    'id_key' => 'id_entreprise',
    'id_param' => 'id_entreprise',
    'list' => is_array($GLOBALS['listeEntreprises'] ?? null) ? $GLOBALS['listeEntreprises'] : [],
    'edit' => $GLOBALS['entreprise_a_modifier'] ?? null,
    'message_success' => (string) ($GLOBALS['messageSuccess'] ?? ''),
    'message_error' => (string) ($GLOBALS['messageErreur'] ?? ''),
    'search_fields' => ['id_entreprise', 'lib_long_entreprise', 'lib_court_en', 'logo', 'email', 'telephone'],
    'add_button_name' => 'btn_add_entreprise',
    'edit_button_name' => 'btn_modifier_entreprise',
    'add_button_label' => 'Ajouter',
    'edit_button_label' => 'Modifier',
    'form_fields' => [
        [
            'name' => 'lib_long_entreprise',
            'label' => 'Libelle long',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Entrez le libelle long',
            'value_key' => 'lib_long_entreprise',
        ],
        [
            'name' => 'lib_court_en',
            'label' => 'Libelle court',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Entrez le libelle court',
            'value_key' => 'lib_court_en',
        ],
        [
            'name' => 'logo',
            'label' => 'Logo',
            'type' => 'text',
            'required' => false,
            'placeholder' => 'URL ou chemin du logo',
            'value_key' => 'logo',
            'attrs' => ['maxlength' => '256'],
        ],
        [
            'name' => 'email',
            'label' => 'Email',
            'type' => 'email',
            'required' => false,
            'placeholder' => 'Email de l\'entreprise',
            'value_key' => 'email',
        ],
        [
            'name' => 'telephone',
            'label' => 'Téléphone',
            'type' => 'text',
            'required' => false,
            'placeholder' => 'Téléphone',
            'value_key' => 'telephone',
        ],
    ],
    'columns' => [
        ['key' => 'id_entreprise', 'label' => 'ID'],
        ['key' => 'lib_long_entreprise', 'label' => 'Libelle Long'],
        ['key' => 'lib_court_en', 'label' => 'Libelle Court'],
        ['key' => 'logo', 'label' => 'Logo'],
        ['key' => 'email', 'label' => 'Email'],
        ['key' => 'telephone', 'label' => 'Téléphone'],
    ],
]);
