<?php
$pageSlug = (string) ($_GET['page'] ?? 'parametres_generaux');

cm_render_param_crud_view([
    'page_slug' => $pageSlug,
    'action' => 'traitements',
    'title' => '',
    'icon' => 'fa-clipboard-list',
    'form_title_add' => '',
    'form_title_edit' => '',
    'id_key' => 'id_traitement',
    'id_param' => 'id_traitement',
    'list' => is_array($GLOBALS['listeTraitements'] ?? null) ? $GLOBALS['listeTraitements'] : [],
    'edit' => $GLOBALS['traitement_a_modifier'] ?? null,
    'message_success' => (string) ($GLOBALS['messageSuccess'] ?? ''),
    'message_error' => (string) ($GLOBALS['messageErreur'] ?? ''),
    'search_fields' => ['lib_traitement', 'label_traitement', 'icone_traitement', 'id_traitement'],
    'add_button_name' => 'btn_add_traitement',
    'edit_button_name' => 'btn_modifier_traitement',
    'add_button_label' => 'Ajouter',
    'edit_button_label' => 'Modifier',
    'form_fields' => [
        [
            'name' => 'lib_traitement',
            'label' => 'Libelle traitement',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Ex: gestion_traitements',
            'value_key' => 'lib_traitement',
        ],
        [
            'name' => 'label_traitement',
            'label' => 'Label traitement',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Ex: Gestion des traitements',
            'value_key' => 'label_traitement',
        ],
        [
            'name' => 'icone_traitement',
            'label' => 'Icone traitement',
            'type' => 'text',
            'required' => true,
            'placeholder' => 'Ex: fa-cogs',
            'value_key' => 'icone_traitement',
        ],
        [
            'name' => 'ordre_traitement',
            'label' => 'Ordre traitement',
            'type' => 'number',
            'required' => true,
            'min' => 1,
            'step' => 1,
            'value_key' => 'ordre_traitement',
        ],
    ],
    'columns' => [
        ['key' => 'id_traitement', 'label' => 'ID'],
        ['key' => 'lib_traitement', 'label' => 'Libelle'],
        ['key' => 'label_traitement', 'label' => 'Label'],
        ['key' => 'icone_traitement', 'label' => 'Icone'],
        ['key' => 'ordre_traitement', 'label' => 'Ordre'],
    ],
]);
